config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :payments do
    resources :refunds
  end

end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id                 :integer          not null, primary key
#  first_name         :string(255)
#  last_name          :string(255)
#  number             :string(255)
#  month              :string(255)
#  year               :integer
#  verification_value :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  token              :string(255)
#  remote_code        :string(255)
#  amount             :decimal(15, 3)
#  currency           :string(255)
#  payment_method_id  :string(255)
#  email              :string(255)
#  message            :string(255)
#  data               :text(65535)
#

class Payment < ActiveRecord::Base

  has_many :refunds, inverse_of: :payment


  def  pay!
    save
    # ActiveMerchant accepts all amounts as Integer values in cents
    response = gateway.purchase((self.amount.to_f * 100).to_i, {card_token: self.token, brand: self.payment_method_id}, {order_id: self.id, email: self.email})

    if response.success?
      card_params = response.params['card']

      puts "Successfully charged $#{self.amount} to the credit card ********#{card_params['last_four_digits']}"

      self.remote_code = response.params['id']
      self.first_name =  card_params['cardholder']['name']
      self.number =  "********#{card_params['last_four_digits']}"
      self.month =  card_params['expiration_month']
      self.year =  card_params['expiration_year']
      self.data = response.params.to_json
      save
    else
      self.errors.add(:base, response.params['message'])
      self.message = response.params['message']
      self.data = response.params.to_json
    end

  end



  def test
    # Use the TrustCommerce test servers
    ActiveMerchant::Billing::Base.mode = :test

    gateway = ActiveMerchant::Billing::TrustCommerceGateway.new(
        :login => 'TestMerchant',
        :password => 'password')

    # ActiveMerchant accepts all amounts as Integer values in cents
    amount = 1000  # $10.00

    # The card verification value is also known as CVV2, CVC2, or CID
    credit_card = ActiveMerchant::Billing::CreditCard.new(
        :first_name         => 'Bob',
        :last_name          => 'Bobsen',
        :number             => '4242424242424242',
        :month              => '8',
        :year               => Time.now.year+1,
        :verification_value => '000')


    # Validating the card automatically detects the card type
    if credit_card.validate.empty?
      # Capture $10 from the credit card
      response = gateway.purchase(amount, credit_card)

      if response.success?
        puts "Successfully charged $#{sprintf("%.2f", amount / 100)} to the credit card #{credit_card.display_number}"
      else
        raise StandardError, response.message
      end
    end
  end

  def real_amount
    amount - refunds.done.map(&:amount).sum
  end

  def gateway

    ActiveMerchant::Billing::Base.mode = :test

    @gateway ||= ActiveMerchant::Billing::MercadopagoGateway.new(
        client_id: Chamber.env.mercadopago.client_id,
        client_secret: Chamber.env.mercadopago.client_secret,
        public_key: Chamber.env.mercadopago.public_key,
        token: Chamber.env.mercadopago.access_token)

  end
end

app/models/refund.rb
# == Schema Information
#
# Table name: refunds
#
#  id          :integer          not null, primary key
#  payment_id  :integer
#  amount      :decimal(15, 3)
#  remote_code :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  message     :string(255)
#  data        :text(65535)
#
# Indexes
#
#  fk_refunds_payment_id  (payment_id)
#

class Refund < ActiveRecord::Base

  belongs_to :payment, inverse_of: :refunds

  scope :done, -> {where.not(remote_code: nil)}

  def refund!

    refund_amount = (self.amount.to_f * 100).to_i if self.amount.present?
    save
    # ActiveMerchant accepts all amounts as Integer values in cents
    response = payment.gateway.refund(refund_amount, payment.remote_code,{order_id: self.id})

    if response.success?

      puts "Successfully refunded $#{self.amount} to the credit card ************#{payment.number}"
      self.remote_code = response.params['id']
      self.amount = response.params['amount']
      self.data = response.params.to_json
      save
    else
      self.errors.add(:base, response.params['message'])
      self.message = response.params['message']
      self.data = response.params.to_json
    end

  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string(255)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :recoverable
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
      redirect_to payments_path
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def index
    @payments = Payment.all.order(created_at: :desc)
  end

  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(token_payment_params)
    @payment.email = params[:email]
    @payment.pay!
    if @payment.errors.any?
      render 'new'
    else
      redirect_to payments_path and return
    end
  end

  def show
    @payment = Payment.find(params[:id])
  end

  private

  def payment_params
    params.require(:payment).permit(:first_name, :last_name, :number, :month, :year, :verification_value)
  end
  def token_payment_params
    params.permit(:token,:payment_method_id, :email, :amount)
  end

end

app/controllers/refunds_controller.rb
class RefundsController < ApplicationController

  def index
    @refunds = Refund.find_by_payment_id(params[:payment_id])
  end

  def create
    @payment = Payment.find(params[:payment_id])
    @refund = @payment.refunds.build(refund_params)
    @refund.refund!
    redirect_to payment_path(@payment)
  end


  private

  def refund_params
    params.permit(:amount)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # From https://github.com/rwz/nestive/blob/master/lib/nestive/layout_helper.rb
  def extends(layout, &block)
    # Make sure it's a string
    layout = layout.to_s

    # If there's no directory component, presume a plain layout name
    layout = "layouts/#{layout}" unless layout.include?('/')

    # Capture the content to be placed inside the extended layout
    @view_flow.get(:layout).replace capture(&block)

    render file: layout
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/refunds_helper.rb
module RefundsHelper
end

app/views/home/index.html.erb
  <header id="header">
    <a name="Home"></a>
    <h1 id="title">One Page RWD</h1>
  </header>

  <section>
    <a name="Icons"></a>
    <h2>Icons!</h2>
    <div class="row text-center">
      <div class="small-12 medium-4 columns">
        <h3><a href="#"><i class="fi-heart"></i><br>Heart</a></h3>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
      </div>
      <div class="small-12 medium-4 columns">
        <h3><a href="#"><i class="fi-star"></i><br>Star</a></h3>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
      </div>
      <div class="small-12 medium-4 columns">
        <h3><a href="#"><i class="fi-plus"></i><br>Plus</a></h3>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
      </div>
    </div>
  </section>

  <section>
    <a name="Picture"></a>
    <h2>Picture!</h2>
    <div class="row text-left">
      <div class="small-12 medium-6 columns">
        <img class="th" src="http://allaboutuarts.ca/wp-content/uploads/2012/07/placeholder.jpg">
      </div>
      <div class="small-12 medium-6 columns">
        <h3>A few words...</h3>
        <blockquote>"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."<cite>Isaac Asimov</cite></blockquote>
      </div>
    </div>
  </section>

  <section>
    <h2>Progress Bar!</h2>
    <div class="row text-center">
      <div class="small-12 columns">
        <div class="progress"> <span class="meter" style="width: 80%"></span> </div>
      </div>
      <a class="button" href="#">Click This Button!</a>
    </div>
  </section>

  <section>
    <h2>Text!</h2>
    <div class="row">
      <div class="small-12 columns">
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
      </div>
    </div>
  </section>

  <section>
    <a name="Contact"></a>
    <h2>Contact!</h2>
    <div class="row">
      <div class="small-12 columns">
        <form>
          <div class="row">
            <div class="small-12 columns">
              <label>Your Name
                <input type="text" />
              </label>
            </div>
            <div class="small-12 columns">
              <label>Your Email Address
                <input type="text" />
              </label>
            </div>
            <div class="small-12 columns">
              <label>Your Message
                <textarea placeholder="Message..."></textarea>
              </label>
            </div>
            <div class="small-12 columns">
              <button type="submit" class="button success expand">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>

  <footer id="footer">
    <div class="row">
      <div class="small-12 medium-6 columns">
        <p class="text-center">&copy; This Website 2014</p>
      </div>
      <div class="small-12 medium-6 columns">
        <ul class="no-bullet text-right">
          <li>(123) 456-7890 <i class="fi-telephone"></i></li>
          <li>me@thiswebsite.com <i class="fi-mail"></i></li>
        </ul>
      </div>
    </div>
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : Chamber.env.app.title %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css">
  </head>

  <body>

  <div class="wrapper">
    <nav id="nav">
      <ul>
        <li class="toggle"><i class="fi-list"></i></li>
        <li><%= link_to('Home', root_path) %></li>
        <li><a href="<%= new_payment_path %>">Pay!</a></li>
      </ul>
    </nav>
      <% if !notice.blank? || !alert.blank? %>
      <h2>&nbsp;</h2>
      <div class="row text-center">
        <% unless notice.blank? %>
          <p class="notice"><%= notice %></p>
        <% end %>
        <% unless alert.blank? %>
          <p class="alert"><%= alert %></p>
        <% end %>
      </div>
      <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<%= extends :single do %>
  <div class="devise">
    <%= yield %>
  </div>
<% end %>

app/views/layouts/single.html.erb
<%= extends :application do %>
  <section>
    <a name="Login"></a>
    <h2><%= content_for :title %></h2>
    <div class="row">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>
  </section>
<% end %>

app/views/payments/_mercadopago_form.html.erb
<script src="https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js"></script>


<% payment.errors.each do |attr, msg| %>
  <div class="alert" ><%= attr.to_s == 'base' ? "#{msg}" : "#{attr}: #{msg}"  %></div>
<% end %>

<form action="<%= payments_path %>" method="post" id="pay" name="pay" >
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <fieldset>
    <ul>
      <li>
        <label for="email">Email</label>
        <input id="email" name="email" value="user@example.com" type="email" placeholder="your email"/>
      </li>
      <li>
        <label for="cardNumber">Credit card number:</label>
        <input type="text" id="cardNumber" data-checkout="cardNumber" value="" />
      </li>
      <li>
        <label for="securityCode">Security code:</label>
        <input type="text" id="securityCode" data-checkout="securityCode" value="123" />
      </li>
      <li>
        <label for="cardExpirationMonth">Expiration month:</label>
        <input type="text" id="cardExpirationMonth" data-checkout="cardExpirationMonth" value="12" />
      </li>
      <li>
        <label for="cardExpirationYear">Expiration year:</label>
        <input type="text" id="cardExpirationYear" data-checkout="cardExpirationYear" value="2019" />
      </li>
      <li>
        <label for="cardholderName">Card holder name:</label>
        <input type="text" id="cardholderName" data-checkout="cardholderName" value="APRO" />
      </li>
      <li>
        <label for="docType">Document type:</label>
        <select id="docType" data-checkout="docType"></select>
      </li>
      <li>
        <label for="docNumber">Document number:</label>
        <input type="text" id="docNumber" data-checkout="docNumber" value="12345678" />
      </li>
      <li>
        <label for="amount">Amount:</label>
        <input type="text" name="amount"  value="12.50" />
      </li>
    </ul>
    <input type="submit" value="Pay!" />
  </fieldset>
</form>

<script type="text/javascript">

  $(function(){


    Mercadopago.setPublishableKey('<%= Chamber.env.mercadopago.public_key %>');
    Mercadopago.getIdentificationTypes();


    function addEvent(el, eventName, handler){
      if (el.addEventListener) {
        el.addEventListener(eventName, handler);
      } else {
        el.attachEvent('on' + eventName, function(){
          handler.call(el);
        });
      }
    };

    function getBin() {
      var ccNumber = document.querySelector('input[data-checkout="cardNumber"]');
      return ccNumber.value.replace(/[ .-]/g, '').slice(0, 6);
    };

  function guessingPaymentMethod(event) {
    var bin = getBin();

    if (event.type == "keyup") {
      if (bin.length >= 6) {
        Mercadopago.getPaymentMethod({
          "bin": bin
        }, setPaymentMethodInfo);
      }
    } else {
      setTimeout(function() {
        if (bin.length >= 6) {
          Mercadopago.getPaymentMethod({
            "bin": bin
          }, setPaymentMethodInfo);
        }
      }, 100);
    }
  };

  function setPaymentMethodInfo(status, response) {
    if (status == 200) {
      // do somethings ex: show logo of the payment method
      var form = document.querySelector('#pay');

      if (document.querySelector("input[name=payment_method_id]") == null) {
        var paymentMethod = document.createElement('input');
        paymentMethod.setAttribute('name', "payment_method_id");
        paymentMethod.setAttribute('type', "hidden");
        paymentMethod.setAttribute('value', response[0].id);

        form.appendChild(paymentMethod);
      } else {
        document.querySelector("input[name=payment_method_id]").value = response[0].id;
      }
    }
  };

    addEvent(document.querySelector('input[data-checkout="cardNumber"]'), 'keyup', guessingPaymentMethod);
    addEvent(document.querySelector('input[data-checkout="cardNumber"]'), 'change', guessingPaymentMethod);

    setTimeout(function(){
      $('input[data-checkout="cardNumber"]').val("4509 9535 6623 3704");
      $('input[data-checkout="cardNumber"]').trigger("change");
      guessingPaymentMethod({type:'keyup'});
    },1000);



  var doSubmit = false;
  addEvent(document.querySelector('#pay'),'submit',doPay);
  function doPay(event){
    event.preventDefault();
    if(!doSubmit){
      var $form = document.querySelector('#pay');

      Mercadopago.createToken($form, sdkResponseHandler); // The function "sdkResponseHandler" is defined below

      return false;
    }
  };

  function sdkResponseHandler(status, response) {
    if (status != 200 && status != 201) {
      alert("verify filled data");
    }else{

      var form = document.querySelector('#pay');

      var card = document.createElement('input');
      card.setAttribute('name',"token");
      card.setAttribute('type',"hidden");
      card.setAttribute('value',response.id);
      form.appendChild(card);
      doSubmit=false;
      form.submit();
    }
  };

  });
</script>

app/views/payments/_payment.html.erb
<div class="small-12 medium-3 columns">
  <%= payment.first_name.blank? ?  '--' : payment.first_name %>
</div>
<div class="small-12 medium-3 columns">
  <%= payment.number.blank? ?  '--' : payment.number %>
</div>
<div class="small-12 medium-2 columns">
  <%= payment.amount.blank? ?  '--' : payment.real_amount %>
</div>
<div class="small-12 medium-2 columns">
  <span title="<%= payment.data  %>"><%= payment.remote_code.blank? ? 'Failed' : 'Executed' %></span>
</div>
<div class="small-12 medium-2 columns">
  <a href="<%= payment_path(payment) %>" >Detail</a>
</div>

app/views/payments/index.html.erb
  <section>
    <a name="Payments"></a>
    <h2>Payments</h2>
    <div class="row text-center">
      <%= render partial: 'payment', collection: @payments, as: :payment %>
    </div>
  </section>

app/views/payments/new.html.erb
  <section>
    <a name="Payments"></a>
    <h2>New Payment</h2>
    <div class="row text-left">
      <%= render 'mercadopago_form', payment: @payment %>
    </div>
  </section>

app/views/payments/show.html.erb
<section>
  <a name="Payments"></a>

  <h2>Payment</h2>

  <div class="row text-right">
    <%= render 'payment', payment: @payment %>
  </div>
  <% unless @payment.remote_code.blank? %>
    <div class="row text-center">
      <h3>Refunds</h3>
    </div>
    <div class="row text-right">
      <% @payment.refunds.each do |refund| %>
        <div class="small-12 medium-1 columns">
          <%= @payment.amount.blank? ? '--' : @payment.amount %>
        </div>
        <div class="small-12 medium-1 columns">
          <%= refund.amount.blank? ? '--' : refund.amount %>
        </div>
        <div class="small-12 medium-2 columns">
          <span title="<%= refund.data  %>"><%= refund.remote_code.blank? ? 'Failed' : 'Executed' %></span>
        </div>
        <div class="small-12 medium-8 columns" >
          <span title="<%= refund.data  %>"><%= refund.message.blank? ? '-' : refund.message  %></span>
        </div>
      <% end %>

    </div>
    <div class="row text-right">
      <form action="<%= payment_refunds_path(@payment) %>" method="post" id="refund" name="refund">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input id="amount" name="amount" value="0.25" type="text"/>
        <input type="submit" value="Refund!">
      </form>
    </div>
    <div class="row text-right">
      <form action="<%= payment_refunds_path(@payment) %>" method="post" id="pay" name="pay">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input type="submit" value="Full Refund"/>
      </form>
    </div>
  <% end %>

</section>